declare module '*.jpg';
declare module '*.mp4';
declare module '*.gif';
declare module '*.mp3';
declare module '*.jpeg';
declare module '*.png';
declare module '*.svg';
declare module 'react-file-base64';
declare module '*';
